#https://opentdb.com/api.php?amount=30&category=9&difficulty=easy&type=boolean
# data courtesy
question_data = [{"type": "boolean",
                  "difficulty": "easy",
                  "category": "General Knowledge",
                  "text": "It is automatically considered entrapment in the United States if the police sell you illegal substances without revealing themselves.",
                  "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Ping-Pong originated in England", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "The mitochondria is the powerhouse of the cell.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "You can legally drink alcohol while driving in Mississippi.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "The National Animal of Scotland is the Unicorn.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "The Lego Group was founded in 1932.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "In 2010, Twitter and the United States Library of Congress partnered together to archive every tweet by American citizens.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "A scientific study on peanuts in bars found traces of over 100 unique specimens of urine.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Pluto is a planet.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Slovakia is a member of European Union-", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "A pasodoble is a type of Italian pasta sauce.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Gumbo is a stew that originated in Louisiana.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Nutella is produced by the German company Ferrero.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "One of Donald Trump&#039;s 2016 Presidential Campaign promises was to build a border wall between the United States and Mexico.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "On average, at least 1 person is killed by a drunk driver in the United States every hour.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "The Sun rises from the North.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Scotland voted to become an independent country during the referendum from September 2014.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Dihydrogen Monoxide was banned due to health risks after being discovered in 1983 inside swimming pools and drinking water.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "&quot;Ananas&quot; is mostly used as the word for Pineapple in other languages.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Jingle Bells was originally meant for Thanksgiving",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "The color orange is named after the fruit.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "When you cry in space, your tears stick to your face.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Video streaming website YouTube was purchased in it&#039;s entirety by Facebook for US$1.65 billion in stock.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "&quot;27 Club&quot; is a term used to refer to a list of famous actors, musicians, and artists who died at the age of 27.",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Romanian belongs to the Romance language family, shared with French, Spanish, Portuguese and Italian. ",
                  "answer": "True", "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "The Great Wall of China is visible from the moon.",
                  "answer": "False", "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Bulls are attracted to the color red.", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "French is an official language in Canada.", "answer": "True",
                  "incorrect_answers": ["False"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Adolf Hitler was born in Australia. ", "answer": "False",
                  "incorrect_answers": ["True"]},
                 {"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
                  "text": "Vietnam&#039;s national flag is a red star in front of a yellow background.",
                  "answer": "False", "incorrect_answers": ["True"]}]
